[package]
name = "fumo-db"
version = "0.1.0"
edition = "2024"

[dependencies]
diesel = { version = "2.2.12", features = ["postgres","r2d2"] }
dotenvy = "0.15"
r2d2 = "0.8"
serde = { version = "1.0.219", features = ["derive"] }
